import java.util.Scanner;
public class Main{
    public static void main(String[] args) {
        System.out.println("---Questao 1---");
        Scanner input = new Scanner(System.in);
        System.out.print("Digite seu nome: ");
        String nome = input.nextLine();
        System.out.println("Ola, "+nome+", seja bem-vindo ao sistema!");
        System.out.println("---Questao 2---");
        System.out.print("Digite a primeira nota: ");
        double nota1 = input.nextDouble();
        System.out.print("Digite a segunda nota: ");
        double nota2 = input.nextDouble();
        System.out.print("Digite a terceira nota: ");
        double nota3 = input.nextDouble();
        double media = (nota1 + nota2 + nota3)/3;
        System.out.printf("Media: %.2f", media);
        System.out.println();
        System.out.println("---Questao 3---");
        int anoAtual = 2026;
        System.out.print("Digite sua data de nascimento: ");
        int dataNascimento = input.nextInt();
        int idade = anoAtual - dataNascimento;
        System.out.printf("Voce completara (ou ja completou) "+idade+" anos em "+dataNascimento );
        System.out.println();
        System.out.println("---Questao 4---");
        System.out.print("Digite uma temperatura em graus Celsius: ");
        double celsius = input.nextDouble();
        double fahrenheint = celsius * 9 / 5 + 32;
        System.out.printf("%.1f graus Celsius = %.1f graus fahrenheit", celsius, fahrenheint);
        System.out.println();
        System.out.println("---Questao 5---");
        System.out.print("Digite um numero inteiro (A): ");
        int a = input.nextInt();
        System.out.print("Digite outro numero inteiro (B): ");
        int b = input.nextInt();
        float divisaoAB = (float) a / (float) b;
        float divisaoBA = (float) b / (float) a;
        System.out.printf("A + B = %d | ", a + b);
        System.out.printf("A - B = %d | ", a - b);
        System.out.printf("B - A = %d | ", b - a);
        System.out.printf("A * B = %d | ", a * b);
        System.out.printf("A / B = %.2f | ", divisaoAB);
        System.out.printf("B / A = %.2f", divisaoBA);
        System.out.println();
        System.out.println("---Questao 6---");
        System.out.print("Digite a distancia total de uma viagem (em Km): ");
        double distancia = input.nextDouble();
        System.out.print("Digite a velocidade media dessa viagem (em Km/h): ");
        double velocidade = input.nextDouble();
        double tempo = distancia/velocidade;
        System.out.printf("Voce gastaria %.2f hora(s) nessa viagem", tempo);
        System.out.println();
        System.out.println("---Questao 7---");
        System.out.print("Digite o tamanho de um raio (em u.c): ");
        double raio = input.nextDouble();
        double perimetro = 2*Math.PI*raio;
        double area = Math.PI * Math.pow(raio,2);
        System.out.printf("Perimetro = %.4f u.c | Area = %.4f u.a", perimetro, area);
        System.out.println();
        System.out.println("---Questao 8---");
        System.out.print("Digite um valor monetario (em dolares): USD");
        double dolares = input.nextDouble();
        System.out.print("Digite a taxa de cambio: ");
        double taxaCambio = input.nextDouble();
        double reais = dolares * taxaCambio;
        System.out.printf("BRL %.2f = USD %.2f", reais, dolares);
        System.out.println();
        System.out.println("---Questao 9---");
        System.out.print("Digite seu peso (em kg): ");
        double peso = input.nextDouble();
        System.out.print("Digite sua altura (em metros): ");
        double altura = input.nextDouble();
        double imc = peso/Math.pow(altura,2);
        System.out.printf("IMC = %.2f", imc);
        System.out.println();
        System.out.println("---Questao 10---");
        System.out.print("Digite o comprimento da base (em u.c): ");
        double base = input.nextDouble();
        System.out.print("Digite o comprimento da altura (em u.c): ");
        double altura2 = input.nextDouble();
        double area2 = base * altura2;
        System.out.printf("Base: %.2f u.c | Altura: %.2f u.c | Area: %.2f u.a", base, altura2, area2);
        System.out.println();
        System.out.println("---Questao 11---");
        int anoatual2 = 2026;
        System.out.print("Digite seu ano de nascimento: ");
        int dataNascimento2 = input.nextInt();
        int idade2 = anoatual2 - dataNascimento2;
        double segundos = idade2 * 365 * 24 * 60 * 60;
        System.out.printf("Voce nasceu em %d, em 2026, voce tem(tinha) %d anos e viveu %.1f segundos", dataNascimento2, idade2, segundos);
        System.out.println();
        System.out.println("---Questao 12---");
        System.out.print("Digite um cateto (A): ");
        double a2 = input.nextDouble();
        System.out.print("Digite outro cateto (B): ");
        double b2 = input.nextDouble();
        double hipotenusa = Math.sqrt(Math.pow(a,2) + Math.pow(b,2));
        System.out.printf("Cateto A: %.2f | Cateto B: %.2f | Hipotenusa: %.2f", a2,b2, hipotenusa);
        System.out.println();
        System.out.println("---Questao 13---");
        System.out.print("Digite o raio de uma esfera (em u.c): ");
        double raio2 = input.nextDouble();
        double volume = 4/3 * Math.PI * Math.pow(raio2,3);
        System.out.printf("Raio: %.2f u.c | Volume: %.2f u.v", raio2, volume);
        System.out.println();
        System.out.println("---Questao 14---");
        System.out.print("Digite uma quantidade de minutos: ");
        double minutosTotal = input.nextDouble();
        double minutos = minutosTotal %60;
        double horas = (minutosTotal - minutos)/60;
        System.out.printf("%.2f correspondem a %.2f horas e %.2f minutos", minutosTotal, horas, minutos);
        System.out.println();
         System.out.println("---Questao 15---");
        System.out.print("Valor total: BRL");
        double subtotal = input.nextDouble();
        double total = subtotal * 11/10;
        System.out.printf("Subtotal: BRL %.2f | Gorjeta: BRL %.2f | Valor final: BRL %.2f",subtotal, subtotal/10, total);
        System.out.println("---Questao 16---");
        System.out.print("Digite o tempo da corrida: (em minutos): ");
        double tempo2 = input.nextDouble();
        System.out.print("Digite a distancia percorrida (em km): ");
        double distancia2 = input.nextDouble();
        double pace = tempo2/distancia2;
        double segundos2 = (Math.round(pace) - pace) * 60;
        pace = Math.floor(pace);
        System.out.println("Seu pace medio foi de "+pace+" minutos e "+segundos2+" segundos por km.");
        System.out.println("---Questao 17---");
        System.out.print("Digite a hora atual: ");
        int horaAtual = input.nextInt();
        System.out.print("Digite os minutos atuais: ");
        int minutoAtual = input.nextInt();
        System.out.print("Digite o tempo de recarga (em minutos): ");
        int tempoRecarga = input.nextInt();
        int minutosAbsolutos = horaAtual * 60 + minutoAtual + tempoRecarga;
        int horasAbsolutas = (minutosAbsolutos/60) % 24;
        minutosAbsolutos %= 60;
        System.out.println("Sua recarga sera concluida as "+horasAbsolutas+":"+minutosAbsolutos);
        System.out.println("---Questao 18---");
        System.out.print("Digite quantos fragmentos seu avatar tem: ");
        int fragmentos = input.nextInt();
        int pocoesMaiores = fragmentos/15;
        fragmentos -= pocoesMaiores*15;
        int pocoesMenores = fragmentos/7;
        fragmentos -= pocoesMenores*7;
        System.out.println("Pocoes Maiores criadas: "+pocoesMaiores +" | Pocoes Menores criadas: "+pocoesMenores +" | Fragmentos Restantes: "+fragmentos);
        System.out.println("---Questao 19---");
        System.out.print("Digite quantos passos que voce deu: ");
        int passos = input.nextInt();
        System.out.print("Digite sua meta diaria: ");
        int meta = input.nextInt();
        int ciclos = passos/meta;
        int restantes = meta - passos%meta;
        System.out.println("Voce atingiu a meta completa "+ciclos+" vez(es). O progresso para o proximo ciclo esta em "+restantes+" passo(s).");
        System.out.println("---Questao 20---");
        System.out.print("Digite quantos alunos existem: ");
        int alunos = input.nextInt();
        System.out.print("Digite a pontuacao total do banco de pontos: ");
        int bancoPontos = input.nextInt();
        int pontuacaoIndividual = bancoPontos/alunos;
        int participacao =  bancoPontos%alunos;
        String taxaRetencao = (double) participacao/bancoPontos*100+"%";
        System.out.println("Pontos por aluno: "+pontuacaoIndividual+"| Pontos transferidos para participacao: "+participacao+" | Taxa de retencao do sistema: "+ taxaRetencao);
        input.close();
    }
}
